services:
  prepare_2_django:
    container_name: prepare_2_django
    build: .
    command: ['python', '/app/prepare2/manage.py', 'runserver', '0:80']
    volumes:
      - .:/app
    env_file:
      - .env

  prepare_2_redis:
    container_name: prepare_2_redis
    image: redis:7.0.4-alpine
  
  prepare_2_beat:
    container_name: prepare_2_beat
    build: .
    command: ['sh', '-c', 'cd /app/prepare2 && celery -A prepare2 beat -l error']
    volumes:
      - .:/app
    env_file:
      - .env

  prepare_2_worker:
    container_name: prepare_2_worker
    build: .
    command: ['sh', '-c', 'cd /app/prepare2 && celery -A prepare2 worker -l error']
    volumes:
      - .:/app
    env_file:
      - .env

  prepare_2_rabbitmq:
    container_name: prepare_2_rabbitmq
    image: rabbitmq:3.10.6-alpine
